In [11]:
# Load Data
import glob 
import pandas as pd

def Carga_All_Files( ):
    regexp='../data/covi*'
    df = pd.DataFrame()
    # Iterate trough LIST DIR and 
    for my_file in glob.glob(regexp):
        this_df = pd.read_csv(my_file)
        this_df['Fecha'] = my_file
        df = pd.concat([df,this_df])
    return df  

#df = Carga_All_Files( )
#nombre_comunidad = 'Madrid'
#df = df[(df['CCAA'] == nombre_comunidad)].sort_values(by='Fecha')
#df

,ID,CCAA,Casos,IA,UCI,Fallecidos,Hospitalizados,Nuevos,Curados,Fecha,TCR,Anticuerpos
13,942,Madrid,29840,363.22,1514,3865,15227.0,2331.0,10827.0,../data/covi0104.csv,NaN,NaN
13,942,Madrid,32155,380.86,1528,4175,15227.0,2315.0,12400.0,../data/covi0204.csv,NaN,NaN
13,942,Madrid,34188,405.54,1506,4483,15050.0,2033.0,13850.0,../data/covi0304.csv,NaN,NaN
13,942,Madrid,36249,410.12,1498,4723,14741.0,2061.0,15362.0,../data/covi0404.csv,NaN,NaN
13,942,Madrid,90,1.35,2,1,NaN,NaN,NaN,../data/covi0503.csv,NaN,NaN
13,942,Madrid,37584,418.44,1499,4941,14551.0,1335.0,16543.0,../data/covi0504.csv,NaN,NaN
13,942,Madrid,137,2.06,2,2,NaN,NaN,NaN,../data/covi0603.csv,NaN,NaN
13,942,Madrid,38723,422.43,1510,5136,14501.0,1139.0,17322.0,../data/covi0604.csv,NaN,NaN
13,942,Madrid,40469,421.96,1494,5371,13950.0,1746.0,18410.0,../data/covi0704.csv,NaN,NaN
13,942,Madrid,42450,418.00,1450,5586,13289.0,1981.0,19836.0,../data/covi0804.csv,NaN,NaN
13,942,Madrid,469,7.04,53,8,NaN,NaN,NaN,../data/covi0903.csv,NaN,NaN
13,942,Madrid,43877,400.86,1433,5800,12853.0,1427.0,21121.0,../data/covi0904.csv,NaN,NaN
13,942,Madrid,782,11.74,77,21,NaN,NaN,NaN,../data/covi1003.csv,NaN,NaN
13,942,Madrid,44783,383.29,1399,5972,12432.0,906.0,22414.0,../data/covi1004.csv,NaN,NaN
13,942,Madrid,1024,15.34,102,31,NaN,NaN,NaN,../data/covi1103.csv,NaN,NaN
13,942,Madrid,45849,365.11,1376,6084,11894.0,1066.0,23663.0,../data/covi1104.csv,NaN,NaN
13,942,Madrid,1388,20.77,135,56,NaN,NaN,NaN,../data/covi1203.csv,NaN,NaN
13,942,Madrid,46587,358.83,1332,6278,11424.0,738.0,24683.0,../data/covi1204.csv,NaN,NaN
13,942,Madrid,1990,29.79,180,81,NaN,NaN,NaN,../data/covi1303.csv,NaN,NaN
13,942,Madrid,47146,346.01,1327,6423,11233.0,559.0,25385.0,../data/covi1304.csv,NaN,NaN
13,942,Madrid,48048,308.24,1299,6568,10753.0,902.0,26247.0,../data/covi1404.csv,NaN,NaN
13,942,Madrid,49526,295.44,1244,6724,10116.0,1478.0,27433.0,../data/covi1504.csv,NaN,NaN
13,942,Madrid,4165,62.07,253,213,NaN,NaN,NaN,../data/covi1603.csv,NaN,NaN
13,942,Madrid,50694,278.22,1206,6877,9653.0,1168.0,28491.0,../data/covi1604.csv,NaN,NaN
13,942,Madrid,4871,72.37,340,355,NaN,NaN,NaN,../data/covi1703.csv,NaN,NaN
13,942,Madrid,51993,267.21,1154,7007,9141.0,1299.0,29436.0,../data/covi1704.csv,NaN,NaN
13,942,Madrid,5637,83.55,491,390,NaN,NaN,NaN,../data/covi1803.csv,NaN,NaN
13,942,Madrid,52946,267.21,1094,7132,8597.0,953.0,30475.0,../data/covi1804.csv,NaN,NaN
13,942,Madrid,6777,100.35,590,498,NaN,NaN,NaN,../data/covi1903.csv,NaN,NaN
13,942,Madrid,54884,259.63,1123,7239,8291.0,1938.0,31313.0,../data/covi1904.csv,NaN,NaN
13,942,Madrid,7165,105.47,678,628,NaN,NaN,NaN,../data/covi2003.csv,NaN,NaN
13,942,Madrid,56963,252.95,1111,7351,8191.0,2079.0,31762.0,../data/covi2004.csv,NaN,NaN
13,942,Madrid,8921,131.82,767,804,7388.0,1756.0,NaN,../data/covi2103.csv,NaN,NaN
13,942,Madrid,57997,263.05,1076,7460,7930.0,1034.0,32277.0,../data/covi2104.csv,NaN,NaN
13,942,Madrid,9702,142.98,834,1021,8441.0,781.0,NaN,../data/covi2203.csv,NaN,NaN
13,942,Madrid,59199,251.36,1024,7577,7464.0,1202.0,33032.0,../data/covi2204.csv,NaN,NaN
13,942,Madrid,10575,151.66,942,1263,9561.0,873.0,2063.0,../data/covi2303.csv,NaN,NaN
13,942,Madrid,60487,249.27,981,7684,7077.0,1288.0,33645.0,../data/covi2304.csv,NaN,NaN
13,942,Madrid,12352,173.64,1050,1535,10443.0,1777.0,2291.0,../data/covi2403.csv,NaN,NaN
13,942,Madrid,61726,201.22,949,7765,6601.0,1097.0,34212.0,../data/covi2404.csv,NaN,NaN
13,942,Madrid,14597,203.02,1150,1825,11153.0,2245.0,3031.0,../data/covi2503.csv,NaN,NaN
13,942,Madrid,17166,236.00,1221,2090,12440.0,2569.0,3882.0,../data/covi2603.csv,NaN,NaN
13,942,Madrid,19243,258.92,1312,2412,13580.0,2077.0,5044.0,../data/covi2703.csv,NaN,NaN
13,942,Madrid,21520,278.84,1404,2757,14211.0,2277.0,6326.0,../data/covi2803.csv,NaN,NaN
13,942,Madrid,22677,287.14,1429,3082,14454.0,1157.0,7491.0,../data/covi2903.csv,NaN,NaN
13,942,Madrid,24090,299.02,1460,3392,14917.0,1413.0,8301.0,../data/covi3003.csv,NaN,NaN
13,942,Madrid,27509,339.74,1514,3603,15140.0,3419.0,9330.0,../data/covi3103.csv,NaN,NaN

In [15]:
! head -3  ../data/covi2504.csv ../data/covi2404.csv

==> ../data/covi2504.csv <==
ID,TCR,Anticuerpos,Casos,IA,UCI,Fallecidos,Hospitalizados,Nuevos,Curados
935,11703,1121,12824,23.66,717,1131,5715,167,4295
936,4922,460,5382,72.24,255,709,2372,55,1929

==> ../data/covi2404.csv <==
ID,CCAA,Casos,IA,UCI,Fallecidos,Hospitalizados,Nuevos,Curados
935,Andalucía,12495,24.08,714,1107,5675,133,3992
936,Aragón,5295,78.53,254,695,2359,34,1781

In [ ]:
def Get_Comunidades_List( ):
    return Carga_All_Files( )['CCAA'].unique()

In [ ]:
#Get_Comunidades_List()

In [ ]:
def Preprocesado():
    df = Carga_All_Files( )
    # Formateamos la fecha
    df['Fecha'].replace({
        '../data/covi': '2020-',
        '.csv'        : ''}, inplace=True, regex=True)
    df['Fecha'] =  pd.to_datetime(df['Fecha'], format='%Y-%d%m')
    # 
    
    return df.sort_values(by='Fecha')

df = Preprocesado()

In [ ]:
import numpy as np

def Enrich_Columns(comunidad):
    del comunidad['ID']
    del comunidad['IA']
    del comunidad['Nuevos']

    if 'Fecha' in comunidad.columns :
        comunidad.set_index('Fecha', inplace=True) 

    # Datos de fallecimientos diarios, en totales y tanto por uno.
    comunidad['Fallecidos hoy absoluto'] = comunidad['Fallecidos'] - comunidad['Fallecidos'].shift(1)
    comunidad['Fallecidos hoy porcentaje'] = comunidad['Fallecidos hoy absoluto']  / comunidad['Fallecidos'] 
    comunidad['Fallecidos hoy variacion respecto ayer'] = comunidad['Fallecidos hoy absoluto'] - comunidad['Fallecidos hoy absoluto'].shift(1)

    # Datos de Casos diarios,  en totales y tanto por uno.
    comunidad['Casos hoy absoluto'] = comunidad['Casos'] - comunidad['Casos'].shift(1)
    comunidad['Casos hoy porcentaje'] = comunidad['Casos hoy absoluto']  / comunidad['Casos'] 
    comunidad['Casos hoy variacion respecto ayer'] = comunidad['Casos hoy absoluto'] - comunidad['Casos hoy absoluto'].shift(1)

    # Convertimos a entero, para quitar decimales
    CONVERT_INT_COLUMNS = ['Fallecidos hoy absoluto', 
                           'Fallecidos hoy variacion respecto ayer',
                           'Casos hoy variacion respecto ayer',
                           'Casos hoy absoluto',
                           'Hospitalizados',
                           'Curados']
    for column in CONVERT_INT_COLUMNS :
        comunidad[column] = comunidad[column].fillna(0)
        comunidad[column] = comunidad[column].astype(np.int64)
    comunidad['Curados hoy absoluto']       = comunidad['Curados'] - comunidad['Curados'].shift(1)
    try : 
        comunidad['Proporcion Curados hoy absoluto / Casos hoy absoluto'] = comunidad['Curados hoy absoluto'] / comunidad['Casos hoy absoluto'] 
    except: 
        pass
    comunidad['Casos excluidos curados'] = comunidad['Casos'] - comunidad['Curados']  
    comunidad['Tasa Mortalidad'] = comunidad['Fallecidos'] / comunidad['Casos'] 
    

    # ordenamos las filas y columnas
    columnsTitles = ['CCAA', 
                     'Casos'     , 'Casos hoy absoluto'     , 'Casos hoy variacion respecto ayer', 'Casos hoy porcentaje'      ,
                     'Fallecidos', 'Fallecidos hoy absoluto', 'Fallecidos hoy variacion respecto ayer', 'Fallecidos hoy porcentaje' ,
                     'Tasa Mortalidad', 
                     'Curados',    'Curados hoy absoluto', 'Casos excluidos curados', 'Proporcion Curados hoy absoluto / Casos hoy absoluto',
                     'UCI',  
                     'Hospitalizados']
    comunidad = comunidad.reindex(columns=columnsTitles)
    comunidad = comunidad.sort_values(by=['Fecha'], ascending=False)
    comunidad = comunidad.rename(columns = {'CCAA':'Lugar'})

    return comunidad

def Get_Comunidad(nombre_comunidad):
    # Trabajamos solo con una comunidad
    df = Preprocesado()
    df = df[(df['CCAA'] == nombre_comunidad)].sort_values(by='Fecha')
    df = Enrich_Columns(df)
    return df

def Get_Nacion():
    df = Preprocesado()
    df = df.sort_values(by='Fecha')
    df = df.groupby(['Fecha']).sum()
    df['CCAA'] = 'España'
    df = Enrich_Columns(df)
    return df

In [ ]:
# Just for debug purposes
def Debug_Get_Comunidad():
    comunidad = Get_Comunidad('Madrid')
    return comunidad

Debug_Get_Comunidad()

In [ ]:
nombre_comunidad='MADRID'    
    # Trabajamos solo con una comunidad
df = Preprocesado()
df
#    df = df[(df['CCAA'] == nombre_comunidad)].sort_values(by='Fecha')
#    df = Enrich_Columns(df)
#    return df

In [ ]:
# Just for debug purposes
def Debug_Get_Nacion():
    return Get_Nacion()

Debug_Get_Nacion()