In [7]:
# Load Data
import glob 
import pandas as pd

def Carga_All_Files( ):
    regexp='../data/covi*'
    df = pd.DataFrame()
    # Iterate trough LIST DIR and 
    for my_file in glob.glob(regexp):
        this_df = pd.read_csv(my_file)
        for columna in [ 'PCR' , 'Antic.' ] :
            if columna in this_df.columns : del this_df[columna]
        this_df = this_df.rename(columns = {'Muertos':'Fallecidos','Hospit.' : 'Hospitalizados'})

        this_df['Fecha'] = my_file
        df = pd.concat([df,this_df])
    return df  

#df = Carga_All_Files( )
#nombre_comunidad = 'Madrid'
#df = df[(df['CCAA'] == nombre_comunidad)].sort_values(by='Fecha')
#df

,ID,CCAA,Casos,IA,UCI,Fallecidos,Hospitalizados,Nuevos,Curados,Fecha
13,942,Madrid,29840,363.22,1514,3865,15227.0,2331.0,10827.0,../data/covi0104.csv
13,942,Madrid,32155,380.86,1528,4175,15227.0,2315.0,12400.0,../data/covi0204.csv
13,942,Madrid,34188,405.54,1506,4483,15050.0,2033.0,13850.0,../data/covi0304.csv
13,942,Madrid,36249,410.12,1498,4723,14741.0,2061.0,15362.0,../data/covi0404.csv
13,942,Madrid,90,1.35,2,1,NaN,NaN,NaN,../data/covi0503.csv
13,942,Madrid,37584,418.44,1499,4941,14551.0,1335.0,16543.0,../data/covi0504.csv
13,942,Madrid,137,2.06,2,2,NaN,NaN,NaN,../data/covi0603.csv
13,942,Madrid,38723,422.43,1510,5136,14501.0,1139.0,17322.0,../data/covi0604.csv
13,942,Madrid,40469,421.96,1494,5371,13950.0,1746.0,18410.0,../data/covi0704.csv
13,942,Madrid,42450,418.00,1450,5586,13289.0,1981.0,19836.0,../data/covi0804.csv
13,942,Madrid,469,7.04,53,8,NaN,NaN,NaN,../data/covi0903.csv
13,942,Madrid,43877,400.86,1433,5800,12853.0,1427.0,21121.0,../data/covi0904.csv
13,942,Madrid,782,11.74,77,21,NaN,NaN,NaN,../data/covi1003.csv
13,942,Madrid,44783,383.29,1399,5972,12432.0,906.0,22414.0,../data/covi1004.csv
13,942,Madrid,1024,15.34,102,31,NaN,NaN,NaN,../data/covi1103.csv
13,942,Madrid,45849,365.11,1376,6084,11894.0,1066.0,23663.0,../data/covi1104.csv
13,942,Madrid,1388,20.77,135,56,NaN,NaN,NaN,../data/covi1203.csv
13,942,Madrid,46587,358.83,1332,6278,11424.0,738.0,24683.0,../data/covi1204.csv
13,942,Madrid,1990,29.79,180,81,NaN,NaN,NaN,../data/covi1303.csv
13,942,Madrid,47146,346.01,1327,6423,11233.0,559.0,25385.0,../data/covi1304.csv
13,942,Madrid,48048,308.24,1299,6568,10753.0,902.0,26247.0,../data/covi1404.csv
13,942,Madrid,49526,295.44,1244,6724,10116.0,1478.0,27433.0,../data/covi1504.csv
13,942,Madrid,4165,62.07,253,213,NaN,NaN,NaN,../data/covi1603.csv
13,942,Madrid,50694,278.22,1206,6877,9653.0,1168.0,28491.0,../data/covi1604.csv
13,942,Madrid,4871,72.37,340,355,NaN,NaN,NaN,../data/covi1703.csv
13,942,Madrid,51993,267.21,1154,7007,9141.0,1299.0,29436.0,../data/covi1704.csv
13,942,Madrid,5637,83.55,491,390,NaN,NaN,NaN,../data/covi1803.csv
13,942,Madrid,52946,267.21,1094,7132,8597.0,953.0,30475.0,../data/covi1804.csv
13,942,Madrid,6777,100.35,590,498,NaN,NaN,NaN,../data/covi1903.csv
13,942,Madrid,54884,259.63,1123,7239,8291.0,1938.0,31313.0,../data/covi1904.csv
13,942,Madrid,7165,105.47,678,628,NaN,NaN,NaN,../data/covi2003.csv
13,942,Madrid,56963,252.95,1111,7351,8191.0,2079.0,31762.0,../data/covi2004.csv
13,942,Madrid,8921,131.82,767,804,7388.0,1756.0,NaN,../data/covi2103.csv
13,942,Madrid,57997,263.05,1076,7460,7930.0,1034.0,32277.0,../data/covi2104.csv
13,942,Madrid,9702,142.98,834,1021,8441.0,781.0,NaN,../data/covi2203.csv
13,942,Madrid,59199,251.36,1024,7577,7464.0,1202.0,33032.0,../data/covi2204.csv
13,942,Madrid,10575,151.66,942,1263,9561.0,873.0,2063.0,../data/covi2303.csv
13,942,Madrid,60487,249.27,981,7684,7077.0,1288.0,33645.0,../data/covi2304.csv
13,942,Madrid,12352,173.64,1050,1535,10443.0,1777.0,2291.0,../data/covi2403.csv
13,942,Madrid,61726,201.22,949,7765,6601.0,1097.0,34212.0,../data/covi2404.csv
13,942,Madrid,14597,203.02,1150,1825,11153.0,2245.0,3031.0,../data/covi2503.csv
13,942,Madrid,62510,194.65,892,7848,6183.0,628.0,34902.0,../data/covi2504.csv
13,942,Madrid,17166,236.00,1221,2090,12440.0,2569.0,3882.0,../data/covi2603.csv
13,942,Madrid,59126,188.18,873,7922,5892.0,307.0,35367.0,../data/covi2604.csv
13,942,Madrid,19243,258.92,1312,2412,13580.0,2077.0,5044.0,../data/covi2703.csv
13,942,Madrid,21520,278.84,1404,2757,14211.0,2277.0,6326.0,../data/covi2803.csv
13,942,Madrid,22677,287.14,1429,3082,14454.0,1157.0,7491.0,../data/covi2903.csv
13,942,Madrid,24090,299.02,1460,3392,14917.0,1413.0,8301.0,../data/covi3003.csv
13,942,Madrid,27509,339.74,1514,3603,15140.0,3419.0,9330.0,../data/covi3103.csv

In [15]:
! head -3  ../data/covi2504.csv ../data/covi2404.csv

==> ../data/covi2504.csv <==
ID,TCR,Anticuerpos,Casos,IA,UCI,Fallecidos,Hospitalizados,Nuevos,Curados
935,11703,1121,12824,23.66,717,1131,5715,167,4295
936,4922,460,5382,72.24,255,709,2372,55,1929

==> ../data/covi2404.csv <==
ID,CCAA,Casos,IA,UCI,Fallecidos,Hospitalizados,Nuevos,Curados
935,Andalucía,12495,24.08,714,1107,5675,133,3992
936,Aragón,5295,78.53,254,695,2359,34,1781

In [17]:
def Get_Comunidades_List( ):
    return Carga_All_Files( )['CCAA'].unique()

In [18]:
#Get_Comunidades_List()

In [19]:
def Preprocesado():
    df = Carga_All_Files( )
    # Formateamos la fecha
    df['Fecha'].replace({
        '../data/covi': '2020-',
        '.csv'        : ''}, inplace=True, regex=True)
    df['Fecha'] =  pd.to_datetime(df['Fecha'], format='%Y-%d%m')
    # 
    
    return df.sort_values(by='Fecha')

In [20]:
import numpy as np

def Enrich_Columns(comunidad):
    del comunidad['ID']
    del comunidad['IA']
    del comunidad['Nuevos']

    if 'Fecha' in comunidad.columns :
        comunidad.set_index('Fecha', inplace=True) 

    # Datos de fallecimientos diarios, en totales y tanto por uno.
    comunidad['Fallecidos hoy absoluto'] = comunidad['Fallecidos'] - comunidad['Fallecidos'].shift(1)
    comunidad['Fallecidos hoy porcentaje'] = comunidad['Fallecidos hoy absoluto']  / comunidad['Fallecidos'] 
    comunidad['Fallecidos hoy variacion respecto ayer'] = comunidad['Fallecidos hoy absoluto'] - comunidad['Fallecidos hoy absoluto'].shift(1)

    # Datos de Casos diarios,  en totales y tanto por uno.
    comunidad['Casos hoy absoluto'] = comunidad['Casos'] - comunidad['Casos'].shift(1)
    comunidad['Casos hoy porcentaje'] = comunidad['Casos hoy absoluto']  / comunidad['Casos'] 
    comunidad['Casos hoy variacion respecto ayer'] = comunidad['Casos hoy absoluto'] - comunidad['Casos hoy absoluto'].shift(1)

    # Convertimos a entero, para quitar decimales
    CONVERT_INT_COLUMNS = ['Fallecidos hoy absoluto', 
                           'Fallecidos hoy variacion respecto ayer',
                           'Casos hoy variacion respecto ayer',
                           'Casos hoy absoluto',
                           'Hospitalizados',
                           'Curados']
    for column in CONVERT_INT_COLUMNS :
        comunidad[column] = comunidad[column].fillna(0)
        comunidad[column] = comunidad[column].astype(np.int64)
    comunidad['Curados hoy absoluto']       = comunidad['Curados'] - comunidad['Curados'].shift(1)
    try : 
        comunidad['Proporcion Curados hoy absoluto / Casos hoy absoluto'] = comunidad['Curados hoy absoluto'] / comunidad['Casos hoy absoluto'] 
    except: 
        pass
    comunidad['Casos excluidos curados'] = comunidad['Casos'] - comunidad['Curados']  
    comunidad['Tasa Mortalidad'] = comunidad['Fallecidos'] / comunidad['Casos'] 
    

    # ordenamos las filas y columnas
    columnsTitles = ['CCAA', 
                     'Casos'     , 'Casos hoy absoluto'     , 'Casos hoy variacion respecto ayer', 'Casos hoy porcentaje'      ,
                     'Fallecidos', 'Fallecidos hoy absoluto', 'Fallecidos hoy variacion respecto ayer', 'Fallecidos hoy porcentaje' ,
                     'Tasa Mortalidad', 
                     'Curados',    'Curados hoy absoluto', 'Casos excluidos curados', 'Proporcion Curados hoy absoluto / Casos hoy absoluto',
                     'UCI',  
                     'Hospitalizados']
    comunidad = comunidad.reindex(columns=columnsTitles)
    comunidad = comunidad.sort_values(by=['Fecha'], ascending=False)
    comunidad = comunidad.rename(columns = {'CCAA':'Lugar'})

    return comunidad

def Get_Comunidad(nombre_comunidad):
    # Trabajamos solo con una comunidad
    df = Preprocesado()
    df = df[(df['CCAA'] == nombre_comunidad)].sort_values(by='Fecha')
    df = Enrich_Columns(df)
    return df

def Get_Nacion():
    df = Preprocesado()
    df = df.sort_values(by='Fecha')
    df = df.groupby(['Fecha']).sum()
    df['CCAA'] = 'España'
    df = Enrich_Columns(df)
    return df

In [22]:
# Just for debug purposes
def Debug_Get_Comunidad():
    comunidad = Get_Comunidad('Madrid')
    return comunidad

Debug_Get_Comunidad()

,Lugar,Casos,Casos hoy absoluto,Casos hoy variacion respecto ayer,Casos hoy porcentaje,Fallecidos,Fallecidos hoy absoluto,Fallecidos hoy variacion respecto ayer,Fallecidos hoy porcentaje,Tasa Mortalidad,Curados,Curados hoy absoluto,Casos excluidos curados,Proporcion Curados hoy absoluto / Casos hoy absoluto,UCI,Hospitalizados
Fecha,,,,,,,,,,,,,,,,
2020-04-26,Madrid,59126,-3384,-4168,-0.057234,7922,74,-9,0.009341,0.133985,35367,465.0,23759,-0.137411,873,5892
2020-04-25,Madrid,62510,784,-455,0.012542,7848,83,2,0.010576,0.125548,34902,690.0,27608,0.880102,892,6183
2020-04-24,Madrid,61726,1239,-49,0.020073,7765,81,-26,0.010431,0.125798,34212,567.0,27514,0.457627,949,6601
2020-04-23,Madrid,60487,1288,86,0.021294,7684,107,-10,0.013925,0.127036,33645,613.0,26842,0.475932,981,7077
2020-04-22,Madrid,59199,1202,168,0.020304,7577,117,8,0.015441,0.127992,33032,755.0,26167,0.628120,1024,7464
2020-04-21,Madrid,57997,1034,-1045,0.017829,7460,109,-3,0.014611,0.128627,32277,515.0,25720,0.498066,1076,7930
2020-04-20,Madrid,56963,2079,141,0.036497,7351,112,5,0.015236,0.129049,31762,449.0,25201,0.215969,1111,8191
2020-04-19,Madrid,54884,1938,985,0.035311,7239,107,-18,0.014781,0.131896,31313,838.0,23571,0.432405,1123,8291
2020-04-18,Madrid,52946,953,-346,0.017999,7132,125,-5,0.017527,0.134703,30475,1039.0,22471,1.090241,1094,8597
2020-04-17,Madrid,51993,1299,131,0.024984,7007,130,-23,0.018553,0.134768,29436,945.0,22557,0.727483,1154,9141
2020-04-16,Madrid,50694,1168,-310,0.023040,6877,153,-3,0.022248,0.135657,28491,1058.0,22203,0.905822,1206,9653
2020-04-15,Madrid,49526,1478,576,0.029843,6724,156,11,0.023200,0.135767,27433,1186.0,22093,0.802436,1244,10116
2020-04-14,Madrid,48048,902,343,0.018773,6568,145,0,0.022077,0.136697,26247,862.0,21801,0.955654,1299,10753
2020-04-13,Madrid,47146,559,-179,0.011857,6423,145,-49,0.022575,0.136236,25385,702.0,21761,1.255814,1327,11233
2020-04-12,Madrid,46587,738,-328,0.015841,6278,194,82,0.030902,0.134759,24683,1020.0,21904,1.382114,1332,11424
2020-04-11,Madrid,45849,1066,160,0.023250,6084,112,-60,0.018409,0.132696,23663,1249.0,22186,1.171670,1376,11894
2020-04-10,Madrid,44783,906,-521,0.020231,5972,172,-42,0.028801,0.133354,22414,1293.0,22369,1.427152,1399,12432
2020-04-09,Madrid,43877,1427,-554,0.032523,5800,214,-1,0.036897,0.132188,21121,1285.0,22756,0.900491,1433,12853
2020-04-08,Madrid,42450,1981,235,0.046667,5586,215,-20,0.038489,0.131590,19836,1426.0,22614,0.719838,1450,13289
2020-04-07,Madrid,40469,1746,607,0.043144,5371,235,40,0.043753,0.132719,18410,1088.0,22059,0.623139,1494,13950
2020-04-06,Madrid,38723,1139,-196,0.029414,5136,195,-23,0.037967,0.132634,17322,779.0,21401,0.683933,1510,14501
2020-04-05,Madrid,37584,1335,-726,0.035520,4941,218,-22,0.044121,0.131466,16543,1181.0,21041,0.884644,1499,14551
2020-04-04,Madrid,36249,2061,28,0.056857,4723,240,-68,0.050815,0.130293,15362,1512.0,20887,0.733624,1498,14741
2020-04-03,Madrid,34188,2033,-282,0.059465,4483,308,-2,0.068704,0.131128,13850,1450.0,20338,0.713232,1506,15050
2020-04-02,Madrid,32155,2315,-16,0.071995,4175,310,48,0.074251,0.129840,12400,1573.0,19755,0.679482,1528,15227
2020-04-01,Madrid,29840,2331,-1088,0.078117,3865,262,51,0.067788,0.129524,10827,1497.0,19013,0.642214,1514,15227
2020-03-31,Madrid,27509,3419,2006,0.124287,3603,211,-99,0.058562,0.130975,9330,1029.0,18179,0.300965,1514,15140
2020-03-30,Madrid,24090,1413,256,0.058655,3392,310,-15,0.091392,0.140805,8301,810.0,15789,0.573248,1460,14917
2020-03-29,Madrid,22677,1157,-1120,0.051021,3082,325,-20,0.105451,0.135909,7491,1165.0,15186,1.006914,1429,14454
2020-03-28,Madrid,21520,2277,200,0.105809,2757,345,23,0.125136,0.128113,6326,1282.0,15194,0.563022,1404,14211
2020-03-27,Madrid,19243,2077,-492,0.107935,2412,322,57,0.133499,0.125344,5044,1162.0,14199,0.559461,1312,13580
2020-03-26,Madrid,17166,2569,324,0.149656,2090,265,-25,0.126794,0.121752,3882,851.0,13284,0.331257,1221,12440
2020-03-25,Madrid,14597,2245,468,0.153799,1825,290,18,0.158904,0.125026,3031,740.0,11566,0.329621,1150,11153
2020-03-24,Madrid,12352,1777,904,0.143863,1535,272,30,0.177199,0.124271,2291,228.0,10061,0.128306,1050,10443
2020-03-23,Madrid,10575,873,92,0.082553,1263,242,25,0.191607,0.119433,2063,2063.0,8512,2.363116,942,9561
2020-03-22,Madrid,9702,781,-975,0.080499,1021,217,41,0.212537,0.105236,0,0.0,9702,0.000000,834,8441
2020-03-21,Madrid,8921,1756,1368,0.196839,804,176,46,0.218905,0.090124,0,0.0,8921,0.000000,767,7388
2020-03-20,Madrid,7165,388,-752,0.054152,628,130,22,0.207006,0.087648,0,0.0,7165,0.000000,678,0
2020-03-19,Madrid,6777,1140,374,0.168216,498,108,73,0.216867,0.073484,0,0.0,6777,0.000000,590,0
2020-03-18,Madrid,5637,766,60,0.135888,390,35,-107,0.089744,0.069186,0,0.0,5637,0.000000,491,0
2020-03-17,Madrid,4871,706,-1469,0.144939,355,142,10,0.400000,0.072880,0,0.0,4871,0.000000,340,0
2020-03-16,Madrid,4165,2175,1573,0.522209,213,132,107,0.619718,0.051140,0,0.0,4165,0.000000,253,0
2020-03-13,Madrid,1990,602,238,0.302513,81,25,0,0.308642,0.040704,0,0.0,1990,0.000000,180,0
2020-03-12,Madrid,1388,364,122,0.262248,56,25,15,0.446429,0.040346,0,0.0,1388,0.000000,135,0
2020-03-11,Madrid,1024,242,-71,0.236328,31,10,-3,0.322581,0.030273,0,0.0,1024,0.000000,102,0
2020-03-10,Madrid,782,313,-19,0.400256,21,13,7,0.619048,0.026854,0,0.0,782,0.000000,77,0
2020-03-09,Madrid,469,332,285,0.707889,8,6,5,0.750000,0.017058,0,0.0,469,0.000000,53,0
2020-03-06,Madrid,137,47,0,0.343066,2,1,0,0.500000,0.014599,0,0.0,137,0.000000,2,0
2020-03-05,Madrid,90,0,0,NaN,1,0,0,NaN,0.011111,0,NaN,90,NaN,2,0

In [ ]:
nombre_comunidad='MADRID'    
    # Trabajamos solo con una comunidad
df = Preprocesado()
df
#    df = df[(df['CCAA'] == nombre_comunidad)].sort_values(by='Fecha')
#    df = Enrich_Columns(df)
#    return df

In [ ]:
# Just for debug purposes
def Debug_Get_Nacion():
    return Get_Nacion()

Debug_Get_Nacion()